## Random Forest Classification

In [1]:
# importing necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
# importing the dataset

dataset = pd.read_csv('Social_Network_Ads.csv')
print(dataset.shape)
print(dataset.head())

(400, 3)
   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0


In [3]:
# Selecting the variables

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X[:5])
print(y[:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
[0 0 0 0 0]


In [5]:
# spliting the dataset into trian and test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 0, test_size = 0.25)

In [6]:
print(X_train[:4])
print(y_train[:4])
print(X_test[:4])
print(y_test[:4])

[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]]
[0 1 0 1]
[[   30 87000]
 [   38 50000]
 [   35 75000]
 [   30 79000]]
[0 0 0 0]


In [7]:
# feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [8]:
# training the Naive Bayes model on the training set

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifer(n_)
classifier.fit(X_train, y_train)


ModuleNotFoundError: No module named 'sklearn.esemble'

In [ ]:
# saving the classifier and the naive bayes model

with open('random_forest_model', 'wb') as file:
    pickle.dump(classifier, file)
    
    


In [ ]:
# make a prediction for age=19 and salary=20000

print(classifier.predict(scaler.transform([[19,20000]])))

In [ ]:
# make and comparing predictions for test set
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis = 1)[:20])

In [ ]:
# making the confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

print(accuracy_score(y_test, y_pred))